### ISSUE TITLE
composing lambdas

### ISSUE THREAD

**Issue by rbpasker** [funcatron/funcatron#2]
please don’t focus on my java-like style, my improper clojure, or my bad semantics, and instead on how to build composite applications as little clojure functions that can have some logic, but creates a dataflow of lambdas

```
(defn process_order
    [order]
    (try 
          (validate_order
           credit_check
       (if (delivery_check) process_order_domestic process_order_intl)
           send_receipt
           )
           (catch Exception e) (reject_order e)
    ) 
)

```

this gets bound to `#http://mywebsite.com/api/process_order
`
and invokes these endpoints and/or lambdas:

```
mywebsite.com/api/credit_check
mywebsite.com/api/delivery_check
mywebsite.com/api/process_order_domestic
mywebsite.com/api/process_order_intl
mywebsite.com/api/send_receipt
mywebsite.com/api/reject_order
```

**Comment by rbpasker** [comment]
can definitely do this in YAML or JSON, too

and here's the Apache Camel list of integration patterns, which shows the kinds of patterns that can be supported in compositions.

http://camel.apache.org/enterprise-integration-patterns.html

**Comment by dpp** [comment]
Interesting.

Definitely want to do chaining and orchestration. Stuff that needs consideration:

* Fan-out/fan-in -- rather than a linear pipeline of functionality, allow multiple services to be invoked (fan out) and have the responses collected (fan-in)
* Fast-fail -- you capture this as an exception. I'd opt for a combination of exception (a system/hardware failure) and short-circuit (e.g., failed validation or credit check)
* Rollback -- if part of the chain fails, roll back changes earlier in the pipeline (e.g., un-reserve inventory if payment fails)

Yeah... revisiting all the J2EE semantics in a distributed system...

I'm not sure how keen I am on doing the description in Clojure... maybe a JSON representation would be better. 

The Camel stuff looks interesting!

**Comment by rbpasker** [comment]
and then there's this, logic in JSON:

http://jsonlogic.com/operations.html
